plugins {
    id 'com.gradleup.shadow' version '9.1.0'
}


repositories {
    maven { url = 'https://repo.opencollab.dev/main' }
}

dependencies {
    compileOnly project(":api")
    compileOnly project(":flows")
    compileOnly 'org.geysermc.floodgate:api:2.2.2-SNAPSHOT'
    compileOnly 'org.geysermc.geyser:api:2.2.0-SNAPSHOT'

    // 单元测试需要在运行期加载 api 和 flows 的类
    testImplementation project(":api")
    testImplementation project(":flows")
}

shadowJar {
    archiveFileName = 'MultiLogin-Core.JarFile'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

artifacts {
    archives shadowJar
}